spring:
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: hunting
          uri: lb://hunting-service
          predicates:
            - Path=/hunting/**

